# Generated by Django 4.0.6 on 2022-07-22 06:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_email_verified_user_is_employer_and_more'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('persian_name', models.CharField(max_length=150, verbose_name='persian name')),
                ('english_name', models.CharField(max_length=150, verbose_name='english name')),
                ('foundation', models.DateField(verbose_name='foundation')),
                ('site', models.URLField(blank=True, verbose_name='site')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='company/banners/', verbose_name='banner')),
                ('number_of_employees', models.PositiveSmallIntegerField(verbose_name='number of employees')),
                ('description', models.TextField(verbose_name='description')),
                ('introduction', models.TextField(verbose_name='introduction')),
                ('culture', models.TextField(verbose_name='culture')),
                ('advantages', models.TextField(verbose_name='advantages')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='address.city', verbose_name='city')),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='accounts.employer', verbose_name='employer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=150, unique=True, verbose_name='type')),
            ],
            options={
                'verbose_name': 'company type',
                'verbose_name_plural': 'company types',
                'db_table': 'company_type',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=150, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('image', models.ImageField(upload_to='employee/images/', verbose_name='images')),
                ('description', models.TextField(verbose_name='description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company', verbose_name='company')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='company.employeetype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'employee',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='company.companytype', verbose_name='type'),
        ),
    ]
