# Generated by Django 4.0.6 on 2022-07-24 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('address', '0001_initial'),
        ('resume', '0001_initial'),
        ('accounts', '0002_user_email_verified_user_is_employer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('cooperation_type', models.CharField(choices=[('0', 'full time'), ('1', 'part time')], max_length=1, verbose_name='cooperation type')),
                ('work_experience', models.CharField(choices=[('0', 'not important'), ('1', 'less than three years'), ('2', 'between three and six years'), ('3', 'more than six years')], max_length=1, verbose_name='work experience')),
                ('Gender', models.CharField(choices=[('0', 'male'), ('1', 'female')], max_length=1, verbose_name='gender')),
                ('degree', models.CharField(choices=[('0', 'associate'), ('1', 'bachelor'), ('2', 'not important')], max_length=1, verbose_name='degree')),
                ('salary', models.PositiveIntegerField(null=True, verbose_name='salary')),
                ('military_status', models.CharField(choices=[('0', 'not important'), ('1', 'served or exempt')], max_length=1, verbose_name='military status')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
            ],
            options={
                'verbose_name': 'job category',
                'verbose_name_plural': 'job categories',
                'db_table': 'job_category',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150, verbose_name='title')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('seen_status', models.CharField(choices=[('0', 'seen'), ('1', 'not seen')], max_length=1, verbose_name='seen status')),
                ('status', models.CharField(choices=[('0', 'waiting'), ('1', 'denied')], max_length=1, verbose_name='status')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_request', to='job.job', verbose_name='job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_request', to='accounts.jobseeker', verbose_name='job seeker')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_request', to='resume.resume', verbose_name='resume')),
            ],
            options={
                'verbose_name': 'job request',
                'verbose_name_plural': 'job requests',
                'db_table': 'job_request',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='job.jobcategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='address.city', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.employer', verbose_name='employer'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(related_name='jobs', to='job.skill', verbose_name='skill'),
        ),
    ]
